name: 'Build'

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-hive/gha-npm-cache@v1

      - name: Build
        run: |
          npm install --legacy-peer-deps
          npm run lint
          npm run test 
          npm run build
