name: 'CI'

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
      - run: npm run lint

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
      - run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Build
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: c-hive/gha-yarn-cache@v2
      - run: npm install --legacy-peer-deps && npm run build
